### ISSUE TITLE
执行结果，拒绝链接

### ISSUE THREAD

**Issue by BlackTravel** [doupoa/Douyin-live-room-data-collection#2]
D:\AAA_SixtyMillion\Douyin-live-room-data-collection-main\douyin>python main.py
[32mINFO[0m:     Started server process [[36m46844[0m]
[32mINFO[0m:     Waiting for application startup.
[92mINFO: [0m| 2022-07-13 13:42:32 | 正在进行数据库连通性测试..
[31mERROR[0m:    Traceback (most recent call last):
  File "D:\Python\python3105\lib\site-packages\aiomysql\connection.py", line 527, in _connect
    self._reader, self._writer = await \
  File "D:\Python\python3105\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python\python3105\lib\site-packages\aiomysql\connection.py", line 88, in _open_connection
    transport, _ = await loop.create_connection(
  File "D:\Python\python3105\lib\asyncio\base_events.py", line 1069, in create_connection
    raise exceptions[0]
  File "D:\Python\python3105\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "D:\Python\python3105\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\Python\python3105\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\Python\python3105\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\Python\python3105\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

**Comment by doupoa** [comment]
很明显是在运行数据库连通性测试时出现的问题。请检查您的MySQL数据库连接，确认地址、端口、数据库账号、数据库密码、数据库名是否正确，建议自行用其他数据库连接软件确认能正常连接后再运行本脚本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doupoa/Douyin-live-room-data-collection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月13日(星期三) 中午1:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[doupoa/Douyin-live-room-data-collection] 执行结果，拒绝链接 (Issue #2)





 
D:\AAA_SixtyMillion\Douyin-live-room-data-collection-main\douyin&gt;python main.py
 �[32mINFO�[0m:     Started server process [�[36m46844�[0m]
 �[32mINFO�[0m:     Waiting for application startup.
 �[92mINFO: �[0m| 2022-07-13 13:42:32 | 正在进行数据库连通性测试..
 �[31mERROR�[0m:    Traceback (most recent call last):
 File "D:\Python\python3105\lib\site-packages\aiomysql\connection.py", line 527, in _connect
 self._reader, self._writer = await 
 File "D:\Python\python3105\lib\asyncio\tasks.py", line 408, in wait_for
 return await fut
 File "D:\Python\python3105\lib\site-packages\aiomysql\connection.py", line 88, in _open_connection
 transport, _ = await loop.create_connection(
 File "D:\Python\python3105\lib\asyncio\base_events.py", line 1069, in create_connection
 raise exceptions[0]
 File "D:\Python\python3105\lib\asyncio\base_events.py", line 1049, in create_connection
 sock = await self._connect_sock(
 File "D:\Python\python3105\lib\asyncio\base_events.py", line 960, in _connect_sock
 await self.sock_connect(sock, address)
 File "D:\Python\python3105\lib\asyncio\proactor_events.py", line 705, in sock_connect
 return await self._proactor.connect(sock, address)
 File "D:\Python\python3105\lib\asyncio\windows_events.py", line 817, in _poll
 value = callback(transferred, key, ov)
 File "D:\Python\python3105\lib\asyncio\windows_events.py", line 604, in finish_connect
 ov.getresult()
 ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。
